version: "3.8"

services:
  mysql-server:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "3306:3306"

  member-service:
    build:
      context: ./MemberService
      dockerfile: Dockerfile
    image: member-service
    ports:
      - "8081:8080"
    depends_on:
      - mysql-server
  
  payment-service:
    build:
      context: ./PaymentService
      dockerfile: Dockerfile
    image: payment-service
    ports:
      - "8082:8080"
    depends_on:
      - mysql-server
  
  delivery-service:
    build:
      context: ./DeliveryService
      dockerfile: Dockerfile
    image: delivery-service
    ports:
      - "8083:8080"
    depends_on:
      - mysql-server