version: "3.8"

services:

  myredis:
    image: redis
    hostname: myredis
    ports:
      - "6379:6379"

  mysql-server:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=ecommerce_db  
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      - myredis

  member-service:
    build:
      context: ./MemberService
      dockerfile: Dockerfile
    image: member-service
    ports:
      - "8081:8080"
    depends_on:
      mysql-server:
        condition: service_healthy
  
  payment-service:
    build:
      context: ./PaymentService
      dockerfile: Dockerfile
    image: payment-service
    ports:
      - "8082:8080"
    depends_on:
      mysql-server:
        condition: service_healthy
  
  delivery-service:
    build:
      context: ./DeliveryService
      dockerfile: Dockerfile
    image: delivery-service
    ports:
      - "8083:8080"
    depends_on:
      mysql-server:
        condition: service_healthy