spring:
  cassandra:
    keyspace-name: catalog
    port: 9042
    contact-points: cassandra-node-0
    local-datacenter: dc1
    schema-action: create_if_not_exists
  datasource:
    url: jdbc:mysql://mysql-server:3306/ecommerce_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
